### ISSUE TITLE
For attached script if we create an offline survey then uploaded cache file is getting failed on server while processing, same script works fine for online survey

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#10]
For attached script if we create an offline survey then uploaded cache file is getting failed on server while processing, same script works fine for online survey.

[Sumeethika.zip](https://github.com/OnePointGlobal/OnePoint-Global-MySurveys-App-iOS/files/1004195/Sumeethika.zip)

**Comment by Chinthan** [comment]
Fix has been added in the new runtime and available in development. It will be released in the next version

**Comment by onepointpb** [comment]
Now the cache file is getting processed.
