### ISSUE TITLE
Not able to take geo location survey, even though we are in survey location if we try to take survey it says "Sorry! you are not in survey location"

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#11]
Not able to take geo location survey, even though we are in survey location if we try to take survey it says "Sorry! you are not in survey location".

**Comment by Manjunath-Ramesh** [comment]
The iPad 1 used for testing do not support geofencing. Please test it with a newer iPad.

**Comment by veereshms** [comment]
Verified.
