### ISSUE TITLE
In profile screen choose from gallery screen is opening in portrait mode when the device is in landscape mode, also whenever we open camera such as to scan barcode then also it opening in portrait mode.

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#12]
In profile screen choose from gallery screen is opening in portrait mode when the device is in landscape mode, also whenever we open camera such as to scan barcode etc. then also it opening in portrait mode.

**Comment by Manjunath-Ramesh** [comment]
The UIImagePickerController class supports portrait mode only. Landscape is not possible in Image picker menu screen. Even in other apps like Skype and Facebook, Image picker works only in portrait.
