### ISSUE TITLE
Header logo image should not be displayed in Settings screen after the panel is changed

### ISSUE THREAD

**Issue by Manjunath-Ramesh** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#19]
Expected: 
Header logo image must set to the navigation bar only in the survey list screen and nowhere else.

**Comment by Manjunath-Ramesh** [comment]
It is fixed. A check is added that sets the header logo only in Survey List screen.

**Comment by onepointpb** [comment]
Verified.
