### ISSUE TITLE
In the demo offline (Pheonix) survey, the validation for the "longGRCNumber" question is not working.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#22]
In iOS app it is accepting simple text and not showing any error, whereas in Studio it is not accepting text.

**Comment by Chinthan** [comment]
Could you please attach the project here.

**Comment by onepointpb** [comment]
Please click [here](https://github.com/OnePointGlobal/OnePoint-Global-MySurveys-App-iOS/files/1362263/script.zip) to download the project.

**Comment by onepointpb** [comment]
This issue is fixed and tested.
