### ISSUE TITLE
In the attached offline script there are few validations that is not working.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#23]
Attached the script below. In the script: 
1. the range validation is not working for "text_q1" question.
2. the range validation is not working for "long_q2" question. But moving to next question and again coming back to the same question displays the boundary value in the input box.
3. the validation message is having extra zeros on the right for "double_q1" . 
For example: "**Answer '10.49' is not in range '10.500000..20.990000**'".
4. for "boolean_q1" by default it should select "No/false" when the user clicks Next.
5. for "num_Loop_q1" there should be three rows in the matrix. In the app, I am getting only two. In this question also the text range validation is not working.

Click [here](https://github.com/OnePointGlobal/OnePoint-Global-MySurveys-App-iOS/files/1361678/061017.zip) to download the script.

**Comment by Chinthan** [comment]
This issue has been fixed and committed to dev branch. It will be moved to live branch in the next release.

**Comment by onepointpb** [comment]
All the above points are fixed except point no. 6.
