### ISSUE TITLE
In the demo offline (Pheonix) survey, the presentation of matrix question is different than the online one.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#24]
This is for both Android and iOS app. Please check the screenshots attached below.
1. online_mandarin
![online_mandarin](https://user-images.githubusercontent.com/26476815/31275208-f4de1b92-aab3-11e7-96f2-e0c2a5aab02e.PNG)

2. online_english
![online_english](https://user-images.githubusercontent.com/26476815/31275209-f4e2d1e6-aab3-11e7-98d8-daf17e7e27a2.PNG)

3. offline_mandarin_iOS
![offline_mandarin](https://user-images.githubusercontent.com/26476815/31275210-f4fe9048-aab3-11e7-9e6e-848c4aaaf169.PNG)

4. offline_english_iOS
![offline_english](https://user-images.githubusercontent.com/26476815/31275211-f502d284-aab3-11e7-813d-9ff8120e6f93.PNG)

**Comment by NeerajOPG** [comment]
The issue has been fixed in Android and we will include it in release. Its not displaying the matrix properly because we are not loading the custom "Question.xsl" defined for that script. we were loading the default "Qusetion.xsl" file.

**Comment by Chinthan** [comment]
This issue has been fixed in IOS and committed to dev branch.

**Comment by onepointpb** [comment]
This issue is fixed and tested.
