### ISSUE TITLE
The images for low and high ratings are not visible for a Rating slider question in offline survey. 

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#25]
The images are present in the project.
Click [here](https://github.com/OnePointGlobal/OnePoint-Global-MySurveys-App-iOS/files/1381749/rating_slider_test.zip) to download the project.

**Comment by Chinthan** [comment]
This issue has been fixed and updated in dev branch. It will be moved to live in next version.

**Comment by onepointpb** [comment]
This is working and tested.
