### ISSUE TITLE
The date displayed in the Survey detail page is incorrect

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#27]
One of the survey was unscheduled and when Tim tried clicking on the survey,the date which is displayed in the Survey detail page is incorrect(future date displayed) in the IOS device[attaching the screenshot]:

![image-1](https://user-images.githubusercontent.com/28919270/32645355-ef850cfe-c60c-11e7-9c1a-d417dac3dea0.jpg)

In case of Android, it shows as Unscheduled.

We couldn't replicate the issue. Can you take a look at it ?

App credentials will be shared via Skype to Manjunath.

**Comment by Manjunath-Ramesh** [comment]
The issue is fixed. It occurred because the Date Formatter was giving different result on Simulator compared to device. It works fine now.

**Comment by onepointpb** [comment]
Verified.
