### ISSUE TITLE
In My Surveys App (iOS) the App notifications are not working

### ISSUE THREAD

**Issue by PallaviPalz** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#3]
In MySurveysnew App V1.4 Alpha IOS platform App notifications are not working

**Comment by Manjunath-Ramesh** [comment]
Working  in the release MySurveys2.0 “Version 1.5 Alpha”

**Comment by Manjunath-Ramesh** [comment]
It is fixed. Notifications are received after updating the certificates on the server.

**Comment by Manjunath-Ramesh** [comment]
iOS notifications are not working after renewing the new certificates with 2.1.2 version app release.

**Comment by vivek-onepoint** [comment]
As tested on getting IOS notifications for mysurveys App is working fine. Can you please re-check.

**Comment by dougmorris** [comment]
@durgajadapolu I will add to the API such that the device token can be supplied at the point of sign in. Will let you know when it is done.

**Comment by durgajadapolu** [comment]
Now push notification are working fine in dev, need to be done some changes for staging to be work. In live we all-ready check and once again I will recheck in live.

**Comment by onepointpb** [comment]
Push notification is working on both staging and Live build. This latest build will be uploaded to App store.
