### ISSUE TITLE
Below script in offline mode is not working correctly in the latest build.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#31]
long_q2 "long_q2 Any whole number between -2,147,483,648 and 2,147,483,647 is valid." long;

1. For positive values (between 0 to 2,147,483,647) it says "not numeric" and for negative values (-1 to -2,147,483,648) the app is crashing.

**Comment by Chinthan** [comment]
This issue is fixed and will be updated in next release.

**Comment by Chinthan** [comment]
fixed and updated in development branch

**Comment by onepointpb** [comment]
Fix verified.
