### ISSUE TITLE
Enabled geosurveys get disabled after navigating to other screen and come back to survey home screen

### ISSUE THREAD

**Issue by Manjunath-Ramesh** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#34]
Geofenced surveys get enabled with a notification and they turn gray(disabled) once the user leaves the screen and return.

**Comment by onepointpb** [comment]
In "By Location" tab if the survey is enabled and the criteria (entry/exit) is changed then syncing the app keeps the survey active. It should be a new survey.

**Comment by Manjunath-Ramesh** [comment]
It is fixed.

**Comment by durgajadapolu** [comment]
It Is fixed

**Comment by dougmorris** [comment]
@onepointpb @hitesh-opg

**Comment by onepointpb** [comment]
This is fixed in the latest build (V 2.1.3).
