### ISSUE TITLE
If a location is having multiple surveys with various entry / exit criteria, then only one survey is getting activated.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#35]
**Geolocation Entry and Exit Criteria**
1. Enable only Entry (without time) : Survey should be enabled with entry and disabled with exit.
2. Enable only Exit (without time): Enter the location. After exiting the location the survey will be enabled and remain same.
3. Enable only Entry (with time) : Survey should be enabled with entry after specified time and disabled with exit.
4. Enable only Exit (with time): Enter the location and stay for specified time. After exiting the location the survey will be enabled and remain same.
5. Enable Entry and Exit (without time): Survey should be enabled with entry and remain enabled on exit.
6. Enable Entry and Exit (with time): Survey should be enabled with entry after a specified time and remain enabled on exit.

**Comment by durgajadapolu** [comment]
This Issue is fixed and available in next version 2.1.3

**Comment by onepointpb** [comment]
In the latest build, I am getting the notifications for multiple surveys. But in the survey list the name of the surveys are same with multiple instances.

**Comment by durgajadapolu** [comment]
It is fixed now updated in live build.

**Comment by onepointpb** [comment]
This was fixed and available in the App store.
