### ISSUE TITLE
On killing the app process on the device and opening it again is not fetching the data correctly.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#36]
On killing the app process on the device and opening it again is not fetching the data correctly.
After investigating we found that if a custom app theme is present other than the default OPG one then this issue is occurring.

**Comment by Manjunath-Ramesh** [comment]
It is fixed. The issue is not related to Theming but to change in database version, it was creating a new DB every time the app is killed and reopened.

**Comment by durgajadapolu** [comment]
This issue is fixed.

**Comment by onepointpb** [comment]
This is fixed and working in Live.
