### ISSUE TITLE
The result of QR code scan in the offline survey overlaps the view bounds.

### ISSUE THREAD

**Issue by Manjunath-Ramesh** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#38]
When a QR code is scanned in  an offline survey, the decoded resulting text is not aligned within the boundary of the view.

**Comment by Manjunath-Ramesh** [comment]
It is fixed. The text is word wrapped within the view bounds.

**Comment by durgajadapolu** [comment]
It is fixed, available in next build 2.1.3

**Comment by onepointpb** [comment]
This is fixed.
