### ISSUE TITLE
Forgot password is almost underneath the login button

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#39]
Tim had reported an issue that the forgot password is almost underneath the login button, can we give 
more space ?
![image-1](https://user-images.githubusercontent.com/28919270/34664361-7e32eb5e-f481-11e7-8459-55cddf0e1642.jpg)

Device used is iPhone X

We checked in IOS and android it looked correct.

Can you please check it further?

**Comment by Chinthan** [comment]
Fixed and updated in development

**Comment by pavithra-opg** [comment]
This is fixed in Live
