### ISSUE TITLE
For Matrix questions, the alignment of rows and columns are not proper inside offline survey.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#40]
Please refer [#31](https://github.com/OnePointGlobal/OnePoint-Global-MySurveys-App-Android/issues/31).

**Comment by Chinthan** [comment]
Fixed and updated in development branch

**Comment by onepointpb** [comment]
For Matrix question the alignment is fixed (V 2.1.3).
