### ISSUE TITLE
Issues in currency question type.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#41]
1. If the range is 10.55 to 99999.99, then the range error message displayed "Answer "0.99" is not in range "10.55..100000"". It should be "Answer "0.99" is not in range "10.55..99999.99"".

2. In the currency input field after 15th digit, every input becomes zero automatically.

**Comment by Chinthan** [comment]
Fixed and updated in development

**Comment by onepointpb** [comment]
Verified.
