### ISSUE TITLE
The repeat/refresh symbol should open the Camera interface, instead of clearing the text in the input box.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#44]
The repeat/refresh symbol should open the Camera interface, instead of clearing the text in the input box.

**Comment by Manjunath-Ramesh** [comment]
I got the new icons for camera image from the design team, working on this. I will update the progress soon.

**Comment by Manjunath-Ramesh** [comment]
It is fixed with the new camera icons and opens camera to re-scan an image.
