### ISSUE TITLE
Issues faced in IOS

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#45]
-Technical page Titles visible when logging into the app.
![image-1](https://user-images.githubusercontent.com/28919270/36198536-e2aaf5e4-119c-11e8-85cb-56f259638ce3.jpg)

- When we have used a brand for the app and we try to refresh, we can see a design under the 
header which doesn’t look  good.
![image-1 1](https://user-images.githubusercontent.com/28919270/36198589-ff12a182-119c-11e8-9e66-2f6b5cd8403e.jpg)

**Comment by Manjunath-Ramesh** [comment]
This is fixed.

**Comment by pavithra-opg** [comment]
Technical words appearing at sync and overlap is issue fixed
