### ISSUE TITLE
Issue with the app theme

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#46]
Each time we sign in to the app, the header background is always orange(default Opg theme) for few seconds irrespective of the theme we had chosen previously. Logo from previous theme appears while the background is orange.
We didn't come across the same issue in Android. 

Let me know if you need any further info

**Comment by Manjunath-Ramesh** [comment]
Fixed and released to QC.

**Comment by pavithra-opg** [comment]
I encountered another issue, say for eg, we have logged in using X account, set a theme for the app and then log out. I try to login with a different account say Y in the same device, the theme which was selected in X account is displayed with OPG logo.
Same scenario was tested in android after a while the theme is changed to the OPG default theme.
Let me know if you need any info.

**Comment by onepointpb** [comment]
It is working now.

**Comment by dougmorris** [comment]
@onepointpb then close it or move to live or something please.

**Comment by onepointpb** [comment]
This is working in the latest build (V 2.1.3) as well.
