### ISSUE TITLE
App is crashing on login.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#47]
Scenario:
1. Sign in with Google. Then Logout.
2. Login with Facebook. The Logout.
3. Now again Sign in with Google. This will crash the app.

**Comment by Manjunath-Ramesh** [comment]
This happens during logout when the offline surveys are still downloading, it won't crash if you wait for the surveys to be downloaded and then logout. It is fixed and will go to QC in the release 2.0.8.

**Comment by durgajadapolu** [comment]
I checked this issue it is working fine

**Comment by hitesh-opg** [comment]
The latest version of the My Surveys app is working as expected.
