### ISSUE TITLE
In My Surveys App IOS platform Survey restart i.e. resume online survey is not working.

### ISSUE THREAD

**Issue by PallaviPalz** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#5]
In My Surveys App IOS platform Survey restart i.e. resume online survey is not working.

**Comment by Manjunath-Ramesh** [comment]
Fixed in the release MySurveys2.0 “Version 1.5 Alpha”

**Comment by veereshms** [comment]
Fix verified.
