### ISSUE TITLE
Google and Facebook sign in buttons are vertically stretched in iPhone X

### ISSUE THREAD

**Issue by Manjunath-Ramesh** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#50]
Google and Facebook sign in buttons are vertically stretched in iPhone X. 
![screen shot 2018-07-11 at 11 58 54 am](https://user-images.githubusercontent.com/26483573/42567818-afb419d6-8528-11e8-973c-8db4981b07a6.png)

**Comment by Manjunath-Ramesh** [comment]
It is fixed, it will go in the release 2.0.9.

**Comment by durgajadapolu** [comment]
It is fixed

**Comment by dougmorris** [comment]
@onepointpb @hitesh-opg

**Comment by hitesh-opg** [comment]
Testing the fix with the help of  @TimSnaith

**Comment by hitesh-opg** [comment]
This is now fixed
