### ISSUE TITLE
Deep Linking Survey is failing to upload media responses

### ISSUE THREAD

**Issue by Manjunath-Ramesh** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#53]
When the app is not logged in, media upload is failing when the survey is taken from clicking a link on the browser.

**Comment by dougmorris** [comment]
@onepointpb @hitesh-opg

**Comment by onepointpb** [comment]
Without logging into the App the media upload is failing. This is still an issue.

**Comment by onepointpb** [comment]
The .htm file was not having the code for deep linking. After adding the deep linking code I am able to upload media responses without logging in.
