### ISSUE TITLE
Forgot password is not working in both Android & iOS

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#55]
When we enter valid email ID to reset the password in Android, it says 'Invalid email ID' while in iOS the app crashes.

**Comment by durgajadapolu** [comment]
App crashing issue is fixed in dev server in iOS, But we need to upload a build to live to fix in live server (App store Build).

**Comment by vivek-onepoint** [comment]
Hi,
Its been fixed from Backend and now it works fine for both Android and IOS in all the servers.
