### ISSUE TITLE
Reset Password email content for English version is not correct if the request is raised through My Surveys App Forgot Password.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#56]
The content is having description about Account Toolkit.

**Comment by vivek-onepoint** [comment]
Hi,

The template is been updated correctly also the issue with the link no redirecting to correct URL is been updated. 

It will be available to test on staging and live on next release.

**Comment by onepointpb** [comment]
The reset password email is modified to reflect the content related to My Surveys App.
