### ISSUE TITLE
Clicking "Reset Password" link in the Reset Password email displays a page with no theme or logo on Live.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#57]
![image](https://user-images.githubusercontent.com/26476815/67184020-64cf5f00-f400-11e9-8bb9-5abb009473c8.png)

Hence, unable to reset password or click on Submit button.

**Comment by vivek-onepoint** [comment]
Hi @onepointpb : I have tested this in Development and Staging its fixed and working fine. But the package is still not updated in Live server. Please have a look to it again once the package is updated to live.

**Comment by vivek-onepoint** [comment]
@onepointpb : Can you re-check this issue. Its been fixed and working fine in Live now.

**Comment by onepointpb** [comment]
It is working now on live.
