### ISSUE TITLE
Offline surveys are not getting loaded in the app while taking surveys.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#58]
The screen shows the page loader icon loading continuously, but nothing gets loaded. (Survey id: 26871 in Live system)

**Comment by durgajadapolu** [comment]
It is fixed available in next testing build, this issue is because of some method is missing in runtime if additional parameters is not empty in OPGPanellistProfile then not able to load offline surveys for those id's.

**Comment by onepointpb** [comment]
The survey is now loading in the latest build (V 2.1.3).
