### ISSUE TITLE
In MySurveys-IOS_V1.5_Alpha app if a panellist has more number of panels and surveys in his/her account then surveys wont load properly in app

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#6]
In MySurveys-IOS_V1.5_Alpha app if a panellist has more number of panels and surveys in his/her account then surveys wont load properly in app, some times it shows surveys and sometimes it shows No surveys available for the selected panel.

**Comment by durgajadapolu** [comment]
This is working fine in version 2.1.3 latest one I have checked it. It might be happen in old version of MySurveys-IOS_V1.5_Alpha app. If any one find it still exist please let me know.

**Comment by onepointpb** [comment]
This is working fine in the latest build (V 2.1.3).
