### ISSUE TITLE
In offline survey email id masking question is not working properly it is getting displayed as star rating question.

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-MySurveys-App-iOS#8]
In offline survey email id masking question is not working properly it is getting displayed as star rating question, the same is working properly in online survey. Kindly refer attached screenshot and i am attaching  studio project for your reference in that "masking_q7" question in email id masking.
Screenshot:
![img_0755](https://cloud.githubusercontent.com/assets/26476914/26100057/64f1eef2-3a4a-11e7-9732-ce099ff6a721.PNG)

Project:
[Sumeethika.zip](https://github.com/OnePointGlobal/OnePoint-Global-MySurveys-App-iOS/files/1003900/Sumeethika.zip)

**Comment by veereshms** [comment]
For this same survey app crashes if we try to resume survey after page question, probably email id masking issue mentioned above and this issue is due to offline runtime.

**Comment by Chinthan** [comment]
Fixed the issue in the latest runtime. It will be updated in the next version release. Provided App for QC testing.

**Comment by onepointpb** [comment]
This is working now.
